import datetime

PRODUCTIONORDERS_PER_DAY = 6
MES_QUEUE_FIXED = 5 # DAYS
BUCKET = 2 # DAYS -> FINISH DATE ERP TO EARLIER
BUFFER = 1 # DAYS -> FINISH DATE ERP EXTRA EARLIER
STARTDATE = datetime.date(2022, 3, 13)
WINDOW = 14 # DAYS to MES (1 week)
DELTA = 14 # DAYS to REQUIREMENT FINISH DATE
PERC_CHANGE = 33/100

stockyard_times = {
    50: 3,
    60: 6,
    70: 15,
    72: 15,
    74: 15
}
